################################################################################
#                       NORTH CAROLINA STATE UNIVERSITY
#
#                              FabScalar Project
#
# FabScalar Copyright (c) 2007-2011 by Niket K. Choudhary, Salil Wadhavkar,
# and Eric Rotenberg.  All Rights Reserved.
#
# Purpose: This is a sample Makefile for generating cores of different
#          configurations using FabGen.  See the README file for details. 
################################################################################

core1: 
	./generate_Processor.pl -fw 4 -fd 1 -fumix 1 1 1 1 -id 2 -iq 32 -sel 8 -rrd 1

core2:
	./generate_Processor.pl -fw 4 -fd 1 -fumix 3 1 1 1 -id 2 -iq 32 -sel 8 -rrd 1

core3: 
	./generate_Processor.pl -fw 5 -fd 1 -fumix 2 1 1 1 -id 2 -iq 32 -sel 8 -rrd 1

core4: 
	./generate_Processor.pl -fw 6 -fd 1 -fumix 3 1 1 1 -id 2 -iq 64 -sel 8 -rrd 1

core5:
	./generate_Processor.pl -fw 8 -fd 1 -fumix 5 1 1 1 -id 2 -iq 128 -sel 16 -rrd 1

core6: 
	./generate_Processor.pl -fw 2 -fd 1 -fumix 1 1 1 1 -id 1 -iq 16 -sel 8 -rrd 1

core7:
	./generate_Processor.pl -fw 4 -fd 1 -fumix 1 1 1 1 -id 1 -iq 16 -sel 8 -rrd 1

core8:
	./generate_Processor.pl -fw 4 -fd 1 -fumix 1 1 1 1 -id 3 -t -iq 32 -sel 8 -rrd 4

core9:
	./generate_Processor.pl -fw 6 -fd 2 -fumix 3 1 1 1 -id 2 -iq 64 -sel 8 -rrd 2

core10:
	./generate_Processor.pl -fw 6 -fd 2 -fumix 3 1 1 1 -id 3 -t -iq 64 -sel 8 -rrd 4

core11:
	./generate_Processor.pl -fw 3 -fd 1 -fumix 1 1 1 1 -id 2 -iq 32 -sel 8 -rrd 1

core12:
	./generate_Processor.pl -fw 1 -fd 1 -fumix 1 1 1 1 -id 2 -iq 32 -sel 8 -rrd 1

core13:
	./generate_Processor.pl -fw 7 -fd 1 -fumix 4 1 1 1 -id 2 -iq 128 -sel 16 -rrd 1

core14:
	./generate_Processor.pl -fw 2 -fd 2 -fumix 1 1 1 1 -id 2 -iq 64 -sel 8 -rrd 1

core15:
	./generate_Processor.pl -fw 4 -fd 2 -fumix 1 1 1 1 -id 2 -iq 64 -sel 8 -rrd 1

core16:
	./generate_Processor.pl -fw 8 -fd 2 -fumix 5 1 1 1 -id 2 -iq 64 -sel 8 -rrd 1

core17:
	./generate_Processor.pl -fw 3 -fd 2 -fumix 1 1 1 1 -id 2 -iq 64 -sel 8 -rrd 1

core18:
	./generate_Processor.pl -fw 5 -fd 2 -fumix 2 1 1 1 -id 2 -iq 64 -sel 8 -rrd 1

core19:
	./generate_Processor.pl -fw 7 -fd 2 -fumix 4 1 1 1 -id 2 -iq 64 -sel 8 -rrd 1

core20: 
	./generate_Processor.pl -fw 4 -fd 1 -fumix 1 1 1 1 -id 2 -iq 32 -sel 8 -rrd 3
